const menu = [
  {
    id: 1,
    title: 'Fujifilm X100T 16 MP Digital Camera (Silver)',
    category: 'men',
    price: 520.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_1.png.pagespeed.ic.DvPBG5vxas.webp',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Samsung CF591 Series Curved 27-Inch FHD',
    category: 'woman',
    price: 610.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_2.png.pagespeed.ic.5v5cwO3kBP.webp',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'Blue Yeti USB Microphone Blackout Edition',
    category: 'woman',
    price: 120.00,
    img:'	https://preview.colorlib.com/theme/coloshop/images/xproduct_3.png.pagespeed.ic.jCfub0gA7s.webp',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'DYMO LabelWriter 450 Turbo Thermal Label',
    category: 'accessories',
    price: 410.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_4.png.pagespeed.ic.WBUe9pni_n.webp',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'Pryma Headphones, Rose Gold & Grey',
    category: 'woman',
    price: 180.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_5.png.pagespeed.ic.qi-sJ2HPdI.webp',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'Fujifilm X100T 16 MP Digital Camera (Silver)',
    category: 'accessories',
    price: 520.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_6.png.pagespeed.ic.zZ9BU77Jfy.webp',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Samsung CF591 Series Curved 27-Inch FHD',
    category: 'woman',
    price: 610.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_7.png.pagespeed.ic.9nA45gs3KX.webp',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'Blue Yeti USB Microphone Blackout Edition',
    category: 'accessories',
    price: 120.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_8.png.pagespeed.ic.zX5uOkWPYV.webp',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'DYMO LabelWriter 450 Turbo Thermal Label',
    category: 'men',
    price: 410.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_9.png.pagespeed.ic.I5FJ0ewNHX.webp',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
  {
    id: 9,
    title: 'Pryma Headphones, Rose Gold & Grey',
    category: 'men',
    price: 180.00,
    img:'https://preview.colorlib.com/theme/coloshop/images/xproduct_10.png.pagespeed.ic.69mYA3FDZH.webp',
    desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
  },
];
export default menu;
